-- ==========================================================
-- Marketing ROI & A/B Testing Analytics
-- SQL Business Analysis
-- Author: Deepa
-- Database: PostgreSQL
-- Total Records: 55,555
--
-- Objective:
-- Analyze marketing campaign performance and generate
-- business insights using SQL.
-- ==========================================================

-- Query 1 — Total Revenue
-- Business Question:
-- What is the total revenue generated from all marketing campaigns?
-- ==========================================
SELECT SUM(revenue) AS total_revenue
FROM marketing.marketing_campaigns;

-- Query 2 — Average ROI
-- Business Question:
-- What is the average Return on Investment (ROI) across all campaigns?
-- ==========================================
SELECT ROUND(CAST(AVG(roi) AS NUMERIC), 2) AS average_roi
FROM marketing.marketing_campaigns;

-- Query 3 — Total Campaigns
-- Business Question:
-- How many marketing campaigns are there?
-- ==========================================
SELECT COUNT(*) AS total_campaigns
FROM marketing.marketing_campaigns;


-- Query 4 — Revenue by Campaign Type
-- Business Question:
-- What is the total revenue generated by each campaign type?
-- ==========================================
SELECT
campaign_type,
SUM(revenue) AS total_revenue
FROM marketing.marketing_campaigns
GROUP BY campaign_type
ORDER BY total_revenue DESC;

-- Query 5 — Revenue by Marketing Channel
-- Business Question:
-- What is the total revenue generated by each marketing channel?
-- ==========================================
SELECT
channel_used,
SUM(revenue) AS total_revenue
FROM marketing.marketing_campaigns
GROUP BY channel_used
ORDER BY total_revenue DESC;

-- Query 6 — Average Engagement Score
-- Business Question:
-- What is the average engagement score across all campaigns?
-- ==========================================
SELECT
ROUND(CAST(AVG(engagement_score) AS NUMERIC), 2) AS avg_engagement
FROM marketing.marketing_campaigns;

-- Query 7 — Best Customer Segment
-- Business Question:
-- Which customer segment generates the most revenue?
-- ==========================================
SELECT
customer_segment,
SUM(revenue) AS revenue
FROM marketing.marketing_campaigns
GROUP BY customer_segment
ORDER BY revenue DESC;

-- Query 8 — Top 10 Highest Revenue Campaigns
-- Business Question:
-- What are the top 10 marketing campaigns by revenue?
-- ==========================================
SELECT
campaign_id,
campaign_type,
revenue
FROM marketing.marketing_campaigns
ORDER BY revenue DESC
LIMIT 10;

-- Query 9 — Top 10 Highest ROI Campaigns
-- Business Question:
-- What are the top 10 marketing campaigns by ROI?
-- ==========================================
SELECT
campaign_id,
campaign_type,
roi
FROM marketing.marketing_campaigns
ORDER BY roi DESC
LIMIT 10;

-- Query 10 — Average Revenue by Language
-- Business Question:
-- What is the average revenue generated by each language?
-- ==========================================
SELECT
language,
ROUND(CAST(AVG(revenue) AS NUMERIC), 2) AS avg_revenue
FROM marketing.marketing_campaigns
GROUP BY language
ORDER BY avg_revenue DESC;

-- Query 11 — Monthly Revenue
-- Business Question:
-- How has total revenue changed month by month?
SELECT
DATE_TRUNC('month', date) AS month,
SUM(revenue) AS total_revenue
FROM marketing.marketing_campaigns
GROUP BY month
ORDER BY month;

-- Query 12: Conversion Rate by Campaign Type
-- Business Question:
-- Which campaign type has the highest conversion rate?
-- ==========================================
SELECT
campaign_type,
ROUND(
CAST(SUM(conversions) AS NUMERIC) / CAST(SUM(clicks) AS NUMERIC) * 100,
2
) AS conversion_rate
FROM marketing.marketing_campaigns
GROUP BY campaign_type
ORDER BY conversion_rate DESC;

-- Query 13: ROI Ranking
-- Business Question:
-- How do campaigns rank based on their ROI?
-- ==========================================
SELECT
campaign_id,
campaign_type,
roi,
RANK() OVER(
ORDER BY roi DESC
) AS roi_rank
FROM marketing.marketing_campaigns;

-- Query 14: Top Campaign in Each Campaign Type
-- Business Question:
-- Which campaign generated the highest revenue within each campaign type?
-- ==========================================
SELECT *
FROM (
SELECT
campaign_id,
campaign_type,
revenue,
ROW_NUMBER() OVER(
PARTITION BY campaign_type
ORDER BY revenue DESC
) AS rn
FROM marketing.marketing_campaigns
) t
WHERE rn = 1;

-- Query 15: Campaigns Above Average Revenue
-- Business Question:
-- Which campaigns generated revenue higher than the overall average revenue?
-- ==========================================
SELECT
campaign_id,
campaign_type,
revenue
FROM marketing.marketing_campaigns
WHERE revenue >
(
SELECT AVG(revenue)
FROM marketing.marketing_campaigns
);